# IMPORTANT: Only add linters whose names start with letters A-M here.
# Linters starting with N-Z should be placed in .golangci3.yml.
issues:
  max-issues-per-linter: 10
  max-same-issues: 3

linters:
  disable-all: true
  enable:
    # !! only add a-m linters here, n-z linters go in .golangci3.yml
    - asasalint
    - asciicheck
    - containedctx
    - contextcheck
    - copyloopvar
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - goconst
    - gocritic
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - mnd

linters-settings:
  copyloopvar:
    check-alias: true
  dogsled:
    max-blank-identifiers: 3
  errcheck:
    ignore: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema:ForceNew|Set
    # "ignore" is deprecated but "exclude-functions" doesn't seem to work or the syntax is non-obvious.
    # https://github.com/kisielk/errcheck#excluding-functions
    # Under exclude-functions are the various attempts at getting it to work, all of which result in d.Set being linted everywhere.
    # exclude-functions:
    #   - github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).Set
    #   - github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceData.Set
    #   - github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema:ForceNew|Set,io:Close
    #   - (github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceData).Set
    #   - github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema:ForceNew|Set
    #   - github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema:ForceNew
    #   - github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema:Set
    #   - github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.Set
    #   - io:Close
  errorlint:
    errorf: false
  goconst:
    ignore-tests: true
    min-occurrences: 6
  gocritic:
    enabled-tags:
      - diagnostic
    disabled-tags:
      - experimental
      - opinionated
      - performance
      - style
  mnd:
    checks:
      - argument
    ignored-functions:
      # AWS Go SDK
      - aws.Int32
      - aws.Int64
      - request.ConstantWaiterDelay
      - request.WithWaiterMaxAttempts
      # AWS Provider
      - nullable.*
      - tfresource.Retry*
      - tfresource.With*
      # Terraform Plugin SDK
      - retry.RetryContext
      - schema.DefaultTimeout
      - validation.*
      # Terraform Plugin Framework
      - int64validator.*
      - listvalidator.*
      - setvalidator.*
      - stringvalidator.*
      - SetDefaultCreateTimeout
      - SetDefaultReadTimeout
      - SetDefaultUpdateTimeout
      - SetDefaultDeleteTimeout
      # Go
      - make
      - strconv.FormatFloat
      - strconv.FormatInt
      - strconv.ParseFloat
      - strconv.ParseInt
      - strings.SplitN

run:
  timeout: 75m
